services:
  - type: web
    name: sfa-chatbot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd backend
      export PYTHONPATH=$PYTHONPATH:$(pwd)
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production 
